# Generated by Django 3.0 on 2021-04-21 00:17

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Compound",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("virtual_id", models.CharField(blank=True, max_length=15, null=True)),
                ("inchi_key", models.CharField(blank=True, max_length=500, null=True)),
                ("smiles", models.CharField(blank=True, max_length=500, null=True)),
                ("dn_id", models.CharField(blank=True, max_length=11, null=True)),
                ("modified", models.DateTimeField(auto_now_add=True)),
                (
                    "ligprep_file",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("epik_file", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "prop_alogd",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=10)),
            ],
            options={
                "ordering": (django.db.models.functions.text.Upper("code"),),
            },
        ),
        migrations.CreateModel(
            name="CompoundOccurrence",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generated", models.DateTimeField(auto_now_add=True)),
                (
                    "compound",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Compound"
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metadata",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        blank=True, default=dict, null=True
                    ),
                ),
                (
                    "compound_occurrences",
                    models.ManyToManyField(to="main.CompoundOccurrence"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="main.Project"
                    ),
                ),
            ],
        ),
    ]
