# Generated by Django 3.2.7 on 2021-10-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_auto_20211025_1741"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="smiles",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
