# Generated by Django 3.2.7 on 2022-03-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_series_receptor_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="series",
            name="receptor_residues",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
