# Generated by Django 3.2.7 on 2022-05-06 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_series_receptor_residues"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="dn_id",
            field=models.CharField(blank=True, max_length=29, null=True),
        ),
    ]
