# Generated by Django 3.2.7 on 2022-06-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_compound_dn_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="maestro_prj",
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
