# Generated by Django 3.2.7 on 2022-05-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_project_maestro_prj"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
