# Generated by Django 3.2.7 on 2022-07-27 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0011_assay_emailer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
