# Generated by Django 3.2.7 on 2022-09-30 20:39

import django.core.validators
from django.db import migrations, models

import basechem.main.models.compound_models
import basechem.mni_common.storage


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_alter_project_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="series",
            name="bound_state_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["sdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="ground_state_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["sdf"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="series",
            name="receptor_file",
            field=models.FileField(
                blank=True,
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdb"]
                    )
                ],
            ),
        ),
    ]
