# Generated by Django 3.2.7 on 2022-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_series_checks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="compound",
            old_name="confgenx_file",
            new_name="confgen_file",
        ),
        migrations.AlterField(
            model_name="series",
            name="name",
            field=models.CharField(default="AddName!", max_length=50),
            preserve_default=False,
        ),
    ]
