# Generated by Django 3.2.7 on 2022-10-05 17:32

from django.db import migrations


def clear_confgen_files(apps, schema_editor):
    """
    For each Compound object, clear the `confgen_file` if it is not
    already blank
    """
    Compound = apps.get_model("main", "Compound")

    for cpd in Compound.objects.all():
        if cpd.confgen_file:
            cpd.confgen_file = ""
            cpd.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_auto_20221005_0853"),
    ]

    operations = [
        migrations.RunPython(clear_confgen_files, migrations.RunPython.noop),
    ]
