# Generated by Django 3.2.7 on 2022-08-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0016_collection_original_upload_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="compoundoccurrence",
            name="molblock",
            field=models.CharField(blank=True, max_length=6000, null=True),
        ),
    ]
