# Generated by Django 3.2.7 on 2022-11-18 18:42

import django.core.validators
from django.db import migrations, models

import basechem.main.models.compound_models
import basechem.mni_common.storage


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0017_compoundoccurrence_molblock"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="structure_available",
        ),
        migrations.AddField(
            model_name="series",
            name="rdock_as",
            field=models.FileField(
                blank=True,
                help_text="Optional: This will be auto-generated on the first rDock run for this series",
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["as"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="rdock_grid",
            field=models.FileField(
                blank=True,
                help_text="Optional: This will be auto-generated on the first rDock run for this series",
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["grd"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="rdock_prm",
            field=models.FileField(
                blank=True,
                help_text="Optional: This will be auto-generated on the first rDock run for this series",
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["prm"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="series",
            name="receptor_file_mol2",
            field=models.FileField(
                blank=True,
                null=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mol2"]
                    )
                ],
            ),
        ),
    ]
