# Generated by Django 3.2.7 on 2022-12-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0018_rdock_files"),
    ]

    operations = [
        migrations.AddField(
            model_name="compoundoccurrence",
            name="gem_id",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="compoundoccurrence",
            name="parent_co",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.compoundoccurrence",
            ),
        ),
        migrations.AddField(
            model_name="compoundoccurrence",
            name="saved_from",
            field=models.CharField(
                choices=[
                    ("align", "align"),
                    ("dock", "dock"),
                    ("torsion", "torsion"),
                    ("user uploaded", "user uploaded"),
                ],
                default="user uploaded",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="compoundoccurrence",
            name="molblock",
            field=models.TextField(blank=True, max_length=6000, null=True),
        ),
    ]
