# Generated by Django 3.2.7 on 2023-01-20 00:16

from django.db import migrations


def null_migration_prep(apps, schema_editor):
    Collection = apps.get_model("main", "Collection")
    col_fields = ("name", "sdf_file")
    for field in col_fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Collection.objects.filter(**filter_param).update(**update_param)

    Compound = apps.get_model("main", "Compound")
    c_fields = (
        "confgen_file",
        "dn_id",
        "epik_file",
        "inchi",
        "ligprep_file",
        "sdf_file",
        "smiles",
        "virtual_id",
    )
    for field in c_fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Compound.objects.filter(**filter_param).update(**update_param)

    CompoundOccurrence = apps.get_model("main", "CompoundOccurrence")
    co_fields = ("gem_id", "molblock")
    for field in co_fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        CompoundOccurrence.objects.filter(**filter_param).update(**update_param)

    Series = apps.get_model("main", "Series")
    s_fields = (
        "bound_state_file",
        "ground_state_file",
        "rdock_as",
        "rdock_grid",
        "rdock_prm",
        "receptor_file",
        "receptor_file_mol2",
        "receptor_residues",
    )
    for field in s_fields:
        filter_param = {"{}__isnull".format(field): True}
        update_param = {field: ""}
        Series.objects.filter(**filter_param).update(**update_param)


class Migration(migrations.Migration):

    dependencies = [
        (
            "main",
            "0019_auto_20221208_1452",
        ),
    ]

    operations = [migrations.RunPython(null_migration_prep, migrations.RunPython.noop)]
