# Generated by Django 3.2.7 on 2023-01-20 00:32

import django.core.validators
from django.db import migrations, models

import basechem.main.models.collection_models
import basechem.main.models.compound_models
import basechem.mni_common.storage


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0020_set_null_default"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="name",
            field=models.CharField(blank=True, default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="collection",
            name="sdf_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.collection_models.collection_files_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="confgen_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.compound_files_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="dn_id",
            field=models.CharField(blank=True, default="", max_length=29),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="epik_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.compound_files_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="inchi",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="ligprep_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.compound_files_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="sdf_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.compound_files_path,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="smiles",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compound",
            name="virtual_id",
            field=models.CharField(blank=True, default="", max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compoundoccurrence",
            name="gem_id",
            field=models.CharField(blank=True, default="", max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="compoundoccurrence",
            name="molblock",
            field=models.TextField(blank=True, default="", max_length=6000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="bound_state_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["sdf"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="ground_state_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["sdf"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="rdock_as",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Optional: This will be auto-generated on the first rDock run for this series",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["as"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="rdock_grid",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Optional: This will be auto-generated on the first rDock run for this series",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["grd"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="rdock_prm",
            field=models.FileField(
                blank=True,
                default="",
                help_text="Optional: This will be auto-generated on the first rDock run for this series",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["prm"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="receptor_file",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdb"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="receptor_file_mol2",
            field=models.FileField(
                blank=True,
                default="",
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.series_files_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mol2"]
                    )
                ],
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="series",
            name="receptor_residues",
            field=models.CharField(blank=True, default="", max_length=500),
            preserve_default=False,
        ),
    ]
