# Generated by Django 3.2.7 on 2023-03-29 22:36

from django.db import migrations, models

import basechem.main.models.compound_models
import basechem.mni_common.storage


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0022_remove_compound_prop_alogd"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="svg_file",
            field=models.FileField(
                blank=True,
                storage=basechem.mni_common.storage.select_media_storage,
                upload_to=basechem.main.models.compound_models.compound_files_path,
            ),
        ),
    ]
