# Generated by Django 3.2.7 on 2023-02-15 00:44
import re

from django.db import migrations


def co_to_c(apps, schema_editor):
    """
    Update gem IDs that were generated before moving analyses to CompoundOccurrences.
    Previously, conformer IDs (that become gem IDs when saved) were linked to the original
    Compound model. Now, they should be linked to the original CompoundOccurrence model
    """
    CompoundOccurrence = apps.get_model("main", "CompoundOccurrence")
    gems = CompoundOccurrence.objects.exclude(gem_id="").select_related("compound")
    for gem in gems:
        gem.gem_id = re.sub(
            "c-\d+", f"c{gem.compound.pk}-co{gem.parent_co.pk}", gem.gem_id
        )
        gem.save()


def c_to_co(apps, schema_editor):
    """
    Undo updating gem IDs that were generated before moving analyses to CompoundOccurrences
    """
    CompoundOccurrence = apps.get_model("main", "CompoundOccurrence")
    gems = CompoundOccurrence.objects.exclude(gem_id="").select_related("compound")
    for gem in gems:
        gem.gem_id = re.sub("c\d+-co\d+", f"c-{gem.compound.pk}", gem.gem_id)
        gem.save()


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0023_compound_svg_file"),
    ]

    operations = [migrations.RunPython(co_to_c, c_to_co)]
