# Generated by Django 3.2.7 on 2023-02-15 00:44
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_enable_rdkit_mols"),
    ]

    operations = [
        migrations.RunSQL(
            'UPDATE public.main_compound SET "rdkit_mol"=mol_from_smiles(smiles::cstring);',
            'UPDATE public.main_compound SET "rdkit_mol"=NULL',
        )
    ]
