# Generated by Django 3.2.7 on 2023-07-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0026_set_rdkit_mols"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="measured_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="compound",
            name="mmps",
            field=models.ManyToManyField(blank=True, to="main.Compound"),
        ),
    ]
