# Generated by Django 3.2.7 on 2023-10-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0027_add_mmp_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compound",
            name="inchi",
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
