# Generated by Django 3.2.7 on 2023-10-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0028_alter_compound_inchi"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
