# Generated by Django 3.2.7 on 2023-10-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0029_compound_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="compound",
            name="is_mmpdb_analogue",
            field=models.BooleanField(default=False),
        ),
    ]
