# Generated by Django 3.2.25 on 2024-04-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0030_compound_mmpdb_generated"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compound",
            name="epik_file",
        ),
    ]
