# Generated by Django 3.2.25 on 2024-06-11 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0031_remove_compound_epik_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="series",
            options={"verbose_name_plural": "Series"},
        ),
    ]
