version: 2
updates:
  # This checks for updates to git submodules every weekday. If it finds an update
  # it will open a PR to update the submodule
  - package-ecosystem: gitsubmodule
    directory: /
    schedule:
      interval: "monthly"
    labels:
      - "mni_common"