# Generated by Django 3.2.7 on 2022-07-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_basechemuser_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="basechemuser",
            name="easter_egg_points",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
